### ISSUE TITLE
Is this working ?

### ISSUE THREAD

**Issue by jdriesen** [herusdianto/vuejs-validation-tutorial#1]
Hi Sir,
Thanks for this tutorial.
I've downloaded evrt from github, but the form doesn't seem to be validated...

Kind regards,
Johnny

**Comment by herusdianto** [comment]
Hi Sir,
Yes I don't know why it's not working with the latest version of vee-validate, I've updated the version of vee-validate in my dependency b598068943914880989034e7fd680341491b0cd2
You can pull this code and run `npm update` it should work.

**Comment by jdriesen** [comment]
Hi,

Thanks for the quick reply !
Gonna give it a try.

Kind regards,
Johnny
